var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                            xx  ",
   "                                                                             x  ",
   "  xxxxx                                                                      x  ",
   "  x                                                              poo         x  ",
   "  x                             oop          p            xx    xxxxx        x  ",
   "  x                          xxxxxxxx   xx   xx      xx                oo    x  ",
   "  x         oo    xxxx                        x!!!!!!x                xxxx   x  ",
   "  x        xxxx                               xxxxxxxx                     t x  ",
   "  x  @                 pp                                                 xxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxxxxxxxx  ",
   "                                                          x!!!!!!!!x            ",
   "                                                          x!!!!!!!!x            ",
   "                                                          xxxxxxxxxx            ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "             xxxxxxxxx                                                                                            ",
   "             x!!!!!!!x                            xxxxxxxxx                                                       ",
   "             x!!!!!!!x                            x!!!!!!!x                                                       ",
   "             xxxxvxxxx                            x!!!!!!!x                x!!!!!x                               ",
   "                                                  xxxxvxxxx                x!!!!!x                                ",
   "                                                                           x!!!!!x                                ",
   "                                      oo                                   xxxvxxx                                ",
   "                                      xxx xxxxxxxx           x                                                    ",
   "                                  xxxx           x           x                                                    ",
   "                               xxx               x        oo x                                                    ",
   "                            xxx                  x        xxxx                                                    ",
   "                         xxx                     x           x                                                    ",
   "                     xxxx                        x           x                                                    ",
   "             oo                                  x           x                                                    ",
   "          xxxxxx                                 xxxx                                                             ",
   "     oo                                          x                                                                ",
   "    xxxxxx                                       x                                                                ",
   "            ppp                                  x        oo x   xxxxx     o           oo     xx ==   xx     o t ",
   "            xxxxxx                               x!!!!!!!xxxxx           xxxx       xxxxxxxx                xxxxxx",
   "                    ooo                          xxxxxxxxxxxxx                                                    ",
   "                   xxxxxx                                                                                         ",
   "                                                                                                                  ",
   "    @                                                                                                             ",
   "xxxxxxxxxxxxxxx      xxxxxxxxxxxxxxx                                              xxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                    x x x xx                                                  ",
   "                                                    x!!!!!!x                                                  ",
   "                                                    x!!!!!!x                                                  ",
   " x                                                  xxxvxxxx                                                  ",
   " x                                                                                                          x ",
   " x                                                                              xxxxxxx                     x ",
   " x                                                                              x!!!!!x                     x ",
   " x                                                                              x!!!!!x                     x ",
   " x                                                                              xxvvxxx                     x ",
   " x                                                                                                          x ",
   " x                                                                                                          x ",
   " x                                                                                                          x ",
   " x                                                                                                          x ",
   " x                                                                                                          x ",
   " x                                     ooo  xxxxxxx                        p                  op            x ",
   " x             pop                   xxxxxxx      x          xxxxx ===    xxxx               xxxxx          x ",
   " x           xxxxx   =    xxxxx                   x p        x                                              x ",
   " x                             x                  xxx        x               xxxx=======  xxxxxxx =       xxx ",
   " x                              x                 x          x                                  x         x x ",
   " x                               x                x        o x                                              x ",
   " x                                x               x        xxx                                              x ",
   " x                                 x           x  x o        x                                              x ",
   " x                                  xxxxx      x  xxx        x                                    ooo t     x ",
   " x                                             x  x         px                                   xxxxxxxxxx x ",
   " x                                         poopx  x        xxx                                              x ",
   " x                                        xxxxxx  x          x                                              x ",
   " x                            po                  x o        x                                              x ",
   " x                          xxxxx                 xxxx       x                                              x ",
   " x                                  xxxxx         x          x                                              x ",
   " x                                                x        o x                                              x ",
   " x            oo        xxxxxxxxx                 x        xxx                                              x ",
   " x           xxxx  ==       = =                   x          x                                              x ",
   " x                      p                         x          x                                              x ",
   " x                     xxxx                       x          x                                              x ",
   " x                                                x  p      ox                                              x ",
   " x             xxxxx                               xxx =   xxx                                              x ",
   " x                                                                                                          x ",
   " x    @   xxxx                                                                                              x ",
   " xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx ",
   "                                                                                                              ",
   "                                                                                                              "],
  [
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  x     x   x   x   x  x        x       x  x     x      x  x                                                  ",
   "   x   x  x   x x   x   x      x x     x        x x    x   x                                                  ",
   "    x x  x     xx   x    x    x   x   x    x   x  x   x    x                                                  ",
   "     x    x   x x   x     x  x     x x     x  x    x x     x                                                  ",
   "     x     x x  xxxxx      x        x      x x      x      x                                                  ",
   "                                                                                                              ",
   "  @                                                        x                                                  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
