var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  xxxxxx       xxxx                xxxxxxxxxxx                                  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                            xx  ",
   "                                                                             x  ",
   "  x                                                                          x  ",
   "  x                                                              poo         x  ",
   "  x                        o    oop          p            xx    xxxxx        x  ",
   "  x              oo       xxx xxxxx   xx   xx      xx                  oo    x  ",
   "  x             xxxx                          x!!!!!!x                xxx    x  ",
   "  x        oo                                 xxxxxxxx                     t x  ",
   "  x  @   xxxx          ppp                                                xxxx  ",
   "  xxxxxxxxxxxxxxx  xxxxxxxxxxx xxxxxxx  xxxxxxx    xxxxxxxx       xxx   xxxxxx  ",
   "                                                          x!!!!!!x              ",
   "                                                          x!!!!!!x              ",
   "                                                          xxxxxxxx              ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "    xxxxxxxxx        xxxxxxxxx    xxxxxx    xxx                    xxxxx             xxxx                         ",
   "             x!!!!!x                              xxxxxxxxx                                                       ",
   "             x!!!!!x                              x!!!!!!!x                                                       ",
   "             xxxxvxx                              x!!!!!!!x                x!!!x                                  ",
   "                                                  xxxxvxxxx                x!!!x                                  ",
   "                                                                           x!!!x                                  ",
   "                                      oo    oooo                               xxxvx                              ",
   "                                      xxx xxxxxxxx           x                                                    ",
   "                                  xxxx           x           x                                                    ",
   "                               xxx               x           x                                                    ",
   "                            xxx                  x           x                                                    ",
   "                         xxx                     x           x                                                    ",
   "                xxx   xxxx                       x           x                                                    ",
   "             oo                                  x           x                                                    ",
   "          xxxxxx                                 x                                                                ",
   "     oo                                          x                                                                ",
   "    xxxx                                         x                 oo         oo                                  ",
   "            ppp                                  x       xxxxx   xxxxx     xxxx          oo     xx == xxxxx     o t",
   "            xxx                                  x!!!!!xxxxx           xxxx       xxxxxxxx                  xxxxxx",
   "                    xxxxx                        xxxxxxxxxxxxx                                                    ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "    @                                                                                                             ",
   "xxxxxxxxxxxxxxx      xxxxxxxxxxxxxxx          xxxxxxxxx         xxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   " x                                                                                                            ",
   " x                                                                                                          x ",
   " x                                                                                                          x ",
   " x                                                                                                          x ",
   " x                                                                                                          x ",
   " x                                                                                                          x ",
   " x                                                                                                          x ",
   " x                                                                                                          x ",
   " x                                                                                                          x ",
   " x                                                                                                          x ",
   " x                                                                                                          x ",
   " x                                     ooo  xxxxxxx                        p                  op            x ",
   " x             pop                  xxxxxxx       x         xxx  =====    xxxx               xxxxx          x ",
   " x           xxxxx   =    xxxxxxx                 x p        x                                              x ",
   " x                                                xxx        x               xxxx======= xxxxxxxx         xxx ",
   " x                                                x          x                                  x         x x ",
   " x                                                x        o x                                              x ",
   " x                                                x        xxx                                              x ",
   " x                                             x  x o        x                                              x ",
   " x                                  xxxxx      x  xxx        x                                    ooo t     x ",
   " x                                             x  x         px                                   xxxxxxxx   x ",
   " x                                         xxxxx  x        xxx                                              x ",
   " x                                        xxxxxx  xx         x                                              x ",
   " x                            po                  xxx        x                                              x ",
   " x                          xxxxx                 xxxx       x                                              x ",
   " x                                  xxxxx         xxx        x                                              x ",
   " x                                                xxxx     o x                                              x ",
   " x            oo        xxxxxxxxx                 x        xxx                                              x ",
   " x           xxxx  ==       = =                   x          x         xxxxxxxxxxxxxxxxxxxxxx               x ",
   " x                      p                         x          x                                              x ",
   " x                     xxxx                       x          x                                              x ",
   " x                                                x  p       x                                              x ",
   " x             xxxxx                               xxx =   xxx                                              x ",
   " x                                                                                                          x ",
   " x    @   xxxx          xxxxx               xxxxxxxxxx         xxxxxx          xxxxxxxxxx                   x ",
   " xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx ",
   "                                                                                                              ",
   "                                                                                                              "],
  [
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  x     x   x   x   x  x        x       x  x     x      x  x                                                  ",
   "   x   x  x   x x   x   x      x x     x        x x    x   x                                                  ",
   "    x x  x     xx   x    x    x   x   x    x   x  x   x    x                                                  ",
   "     x    x   x x   x     x  x     x x     x  x    x x     x                                                  ",
   "     x     x x  xxxxx      x        x      x x      x      x                                                  ",
   "                                                                                                              ",
   "  @                                                        x                                                  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
